# Generated by Django 6.0.7 on 2026-07-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_presaveuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='presaveuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
