# Generated by Django 6.0.7 on 2026-07-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presaveuser',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
